<h2> 23년 1월을 예제로 데이터를 어떻게 가공하는지 보여주는 예시

In [188]:
import pandas as pd
rental_2301 = pd.read_csv('서울특별시 공공자전거 이용정보(시간대별)_2301.csv', encoding='cp949')
sample = pd.read_csv('[상위 30개]2023년 따릉이 대여소별 대여반납건수(반납건수-대여건수 내림차순)_240512.csv', encoding='cp949')

In [189]:
# 23년 1월의 공공자전거 이용정보 데이터 확인
rental_2301

,대여일자,대여시간,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,2023-01-01,0,433,433. 을지로입구역 2번출구,정기권,NaN,~10대,1,44.24,0.42,1831.45,8
1,2023-01-01,0,2032,2032. 이수역 11번출구쪽,정기권,NaN,~10대,1,7.11,0.06,276.06,4
2,2023-01-01,0,744,744. 신목동역 2번 출구,정기권,NaN,20대,1,25.05,0.24,1020.46,7
3,2023-01-01,0,1029,1029. 성내어울터,정기권,NaN,20대,1,34.05,0.20,859.74,4
4,2023-01-01,0,1153,"1153. 발산역 1번, 9번 인근 대여소",정기권,NaN,20대,2,141.49,1.31,5675.10,78
...,...,...,...,...,...,...,...,...,...,...,...,...
1473426,2023-01-31,23,1008,1008. 암사역 3번출구(국민은행앞),정기권,M,기타,1,38.85,0.30,1307.99,10
1473427,2023-01-31,23,1224,1224. 아시아지하보도 2번 출구,정기권,M,기타,1,55.01,0.56,2395.18,22
1473428,2023-01-31,23,209,209. 유진투자증권빌딩 앞,정기권,M,기타,1,15.96,0.14,620.00,4
1473429,2023-01-31,23,1318,1318. 길음역 3번출구 뒤,정기권,M,기타,1,0.00,0.00,0.10,42
1473430,2023-01-31,23,2116,2116. 에이스에이존빌딩,정기권,M,기타,1,25.52,0.20,859.35,4

In [190]:
# 표본으로 활용할 반납-대여가 원활히 되지 않는 상위 30개 대여소 데이터 확인
sample

    대여소번호                      대여소명   자치구    대여건수    반납건수  반납건수-대여건수
0     574                  아차산역4번출구   광진구   39597   22567     -17030
1     711               신일해피트리아파트 앞   양천구   17370    2900     -14470
2    3513                상왕십리역 1번출구   성동구   30022   19156     -10866
3     623              서울시립대 정문 앞 B  동대문구   27664   16886     -10778
4    1126  우장산역 1번출구옆(우장산아이파크105동앞)   강서구   27603   16930     -10673
5     207              여의나루역 1번출구 앞  영등포구  113094  102439     -10655
6     584                  광진광장 교통섬   광진구   42593   31953     -10640
7    1692                  온곡초교 교차로   노원구   27991   18358      -9633
8    2712                 화곡터널입구교차로   강서구   13681    4377      -9304
9    4591                   신길자이아파트  영등포구   10961    2570      -8391
10   2405                 청담공원앞 교차로   강남구   12461    4288      -8173
11   3758                서울남부출입국관리소   강서구   29369   21373      -7996
12    434              신당 래미안 버스정류장    중구    8248     489      -7759
13   2349            역삼빌딩 앞(하나은행 옆)   강남구   10604    3410      -7194
14   1924                 삼부르네상스파크빌   구로구   14338    7272      -7066
15   1430                      중랑구청   중랑구   15527    8599      -6928
16   1199                 우장산역 3번출구   강서구   24029   17105      -6924
17    213                       KT앞  영등포구   34647   27768      -6879
18   1428                    원묵고등학교   중랑구   16544    9700      -6844
19    497                 합정동주민센터 앞   마포구   32358   25642      -6716
20   4621                   남산도서관 앞   용산구    8749    2124      -6625
21   4221         솔리스타오피스텔(공덕동주민센터)   마포구    8168    1808      -6360
22    162                  봉원고가차도 밑  서대문구    9703    3343      -6360
23    725                양강중학교앞 교차로   양천구   10013    3809      -6204
24   3642              LH강남힐스테이트아파트   강남구    9612    3508      -6104
25    474        동대문역사문화공원역 1번출구 뒤편    중구   30286   24202      -6084
26   4009                     월계프라자   노원구    9922    3851      -6071
27   1854             가산아네스트 오피스텔 앞   금천구    9901    3871      -6030
28    720                서울강월초등학교 앞   양천구   11383    5400      -5983
29   1175               대한항공 인력개발센터   강서구   20441   14596      -5845

In [191]:
# 23년 1월 데이터에서 필요하지 않은 변수 제거
rental_2301.drop(['대여구분코드', '성별', '연령대코드', '운동량', '탄소량', '이동거리(M)', '이용시간(분)'], axis=1, inplace=True)
rental_2301

               대여일자  대여시간  대여소번호                     대여소명  이용건수
0        2023-01-01     0    433         433. 을지로입구역 2번출구     1
1        2023-01-01     0   2032         2032. 이수역 11번출구쪽     1
2        2023-01-01     0    744          744. 신목동역 2번 출구     1
3        2023-01-01     0   1029              1029. 성내어울터     1
4        2023-01-01     0   1153  1153. 발산역 1번, 9번 인근 대여소     2
...             ...   ...    ...                      ...   ...
1473426  2023-01-31    23   1008    1008. 암사역 3번출구(국민은행앞)     1
1473427  2023-01-31    23   1224      1224. 아시아지하보도 2번 출구     1
1473428  2023-01-31    23    209          209. 유진투자증권빌딩 앞     1
1473429  2023-01-31    23   1318         1318. 길음역 3번출구 뒤     1
1473430  2023-01-31    23   2116           2116. 에이스에이존빌딩     1

[1473431 rows x 5 columns]

In [192]:
# 표본 대여소만 활용하기 위한 데이터 처리
# 표본 대여소의 대여소 번호 목록을 담은 리스트 생성
sample_num = sorted(list(sample['대여소번호']))
del_idx_list = []

# 23년 1월 데이터에서 제거할 인덱스 추출
for idx in rental_2301.index:
    rental_num = rental_2301.loc[idx]['대여소번호']
    if rental_num not in sample_num:
        del_idx_list.append(idx)

In [193]:
# 표본으로 취할 대여소의 대여소번호 목록
sample_num

[162,
 207,
 213,
 434,
 474,
 497,
 574,
 584,
 623,
 711,
 720,
 725,
 1126,
 1175,
 1199,
 1428,
 1430,
 1692,
 1854,
 1924,
 2349,
 2405,
 2712,
 3513,
 3642,
 3758,
 4009,
 4221,
 4591,
 4621]

In [194]:
# 23년 1월 데이터에서 표본 대여소 외 대여소 정보 삭제
rental_2301.drop(del_idx_list, inplace=True)

In [195]:
#대여소명 (233. 정류소이름) -> (정류소이름) 으로 변경
new_name = []

for name in list(rental_2301['대여소명']):
    # '.'을 기준으로 분리 후 정류소 이름만 취하기
    name = name.split('.')[1]
    # 앞뒤 공백 제거
    name = name.strip()
    new_name.append(name)

In [196]:
# 대여소명 열 이름만 남도록 수정
rental_2301['대여소명'] = new_name

In [197]:
# 대여소번호와 대여소명이 분리된 것 확인
rental_2301

               대여일자  대여시간  대여소번호           대여소명  이용건수
110      2023-01-01     0    207   여의나루역 1번출구 앞     1
313      2023-01-01     0    213            KT앞     1
335      2023-01-01     0   1854  가산아네스트 오피스텔 앞     1
337      2023-01-01     0   1199      우장산역 3번출구     1
371      2023-01-01     0   3758     서울남부출입국관리소     1
...             ...   ...    ...            ...   ...
1473216  2023-01-31    23   4591        신길자이아파트     1
1473250  2023-01-31    23   4009          월계프라자     1
1473285  2023-01-31    23   1199      우장산역 3번출구     1
1473390  2023-01-31    23    497      합정동주민센터 앞     1
1473405  2023-01-31    23    207   여의나루역 1번출구 앞     1

[22264 rows x 5 columns]

In [198]:
list(rental_2301['대여소명'])

['여의나루역 1번출구 앞',
 'KT앞',
 '가산아네스트 오피스텔 앞',
 '우장산역 3번출구',
 '서울남부출입국관리소',
 '청담공원앞 교차로',
 '우장산역 3번출구',
 '월계프라자',
 '우장산역 3번출구',
 '여의나루역 1번출구 앞',
 '서울강월초등학교 앞',
 '동대문역사문화공원역 1번출구 뒤편',
 '동대문역사문화공원역 1번출구 뒤편',
 '월계프라자',
 '서울시립대 정문 앞',
 '동대문역사문화공원역 1번출구 뒤편',
 '양강중학교앞 교차로',
 '온곡초교 교차로',
 '온곡초교 교차로',
 '솔리스타오피스텔(공덕동주민센터)',
 '신당 래미안 버스정류장',
 '봉원고가차도 밑',
 '광진광장 교통섬',
 '신당 래미안 버스정류장',
 '월계프라자',
 '서울남부출입국관리소',
 '서울남부출입국관리소',
 '동대문역사문화공원역 1번출구 뒤편',
 '광진광장 교통섬',
 '여의나루역 1번출구 앞',
 '서울시립대 정문 앞',
 'KT앞',
 '여의나루역 1번출구 앞',
 '우장산역 3번출구',
 '봉원고가차도 밑',
 '남산도서관 앞',
 '여의나루역 1번출구 앞',
 '동대문역사문화공원역 1번출구 뒤편',
 '동대문역사문화공원역 1번출구 뒤편',
 '상왕십리역 1번출구',
 '월계프라자',
 'KT앞',
 '아차산역4번출구',
 '남산도서관 앞',
 '우장산역 3번출구',
 '남산도서관 앞',
 '남산도서관 앞',
 '대한항공 인력개발센터',
 'LH강남힐스테이트아파트',
 '양강중학교앞 교차로',
 '동대문역사문화공원역 1번출구 뒤편',
 '서울남부출입국관리소',
 '서울남부출입국관리소',
 '우장산역 3번출구',
 '삼부르네상스파크빌',
 '중랑구청',
 '합정동주민센터 앞',
 'KT앞',
 '대한항공 인력개발센터',
 '우장산역 3번출구',
 '원묵고등학교',
 'KT앞',
 '동대문역사문화공원역 1번출구 뒤편',
 '동대문역사문화공원역 1번출구 뒤편',
 '우장산역 3번출구',
 '서울남부출입국관리소',
 '중랑구청',
 '여의나루역 1번출구 앞',
 '우장산역 3번출구',
 '동대문역사문화공원역 1번출구 뒤편',
 '신당 래미안 버스정류장',
 '청담공원앞 교차로',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '우장산역 3번출구',
 '삼부르네상스파크빌',
 '동대문역사문화공원역 1번출구 뒤편',
 '양강중학교앞 교차로',
 '광진광장 교통섬',
 '광진광장 교통섬',
 '온곡초교 교차로',
 '우장산역 3번출구',
 '여의나루역 1번출구 앞',
 '월계프라자',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '동대문역사문화공원역 1번출구 뒤편',
 '서울남부출입국관리소',
 '가산아네스트 오피스텔 앞',
 '신당 래미안 버스정류장',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '아차산역4번출구',
 '동대문역사문화공원역 1번출구 뒤편',
 'LH강남힐스테이트아파트',
 '아차산역4번출구',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 '아차산역4번출구',
 '아차산역4번출구',
 '신길자이아파트',
 '광진광장 교통섬',
 '온곡초교 교차로',
 '광진광장 교통섬',
 'KT앞',
 '여의나루역 1번출구 앞',
 '동대문역사문화공원역 1번출구 뒤편',
 '월계프라자',
 '광진광장 교통섬',
 '삼부르네상스파크빌',
 '온곡초교 교차로',
 '여의나루역 1번출구 앞',
 '서울강월초등학교 앞',
 '신일해피트리아파트 앞',
 'LH강남힐스테이트아파트',
 '동대문역사문화공원역 1번출구 뒤편',
 '온곡초교 교차로',
 '동대문역사문화공원역 1번출구 뒤편',
 '광진광장 교통섬',
 '합정동주민센터 앞',
 '아차산역4번출구',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 '여의나루역 1번출구 앞',
 '화곡터널입구교차로',
 '봉원고가차도 밑',
 '대한항공 인력개발센터',
 'LH강남힐스테이트아파트',
 '서울강월초등학교 앞',
 '남산도서관 앞',
 '남산도서관 앞',
 '남산도서관 앞',
 '남산도서관 앞',
 '원묵고등학교',
 '남산도서관 앞',
 '대한항공 인력개발센터',
 '상왕십리역 1번출구',
 '아차산역4번출구',
 '남산도서관 앞',
 '우장산역 3번출구',
 '아차산역4번출구',
 '양강중학교앞 교차로',
 '온곡초교 교차로',
 '우장산역 3번출구',
 '아차산역4번출구',
 '온곡초교 교차로',
 '아차산역4번출구',
 '동대문역사문화공원역 1번출구 뒤편',
 '여의나루역 1번출구 앞',
 '온곡초교 교차로',
 '온곡초교 교차로',
 '중랑구청',
 '화곡터널입구교차로',
 '합정동주민센터 앞',
 '신일해피트리아파트 앞',
 '아차산역4번출구',
 '서울남부출입국관리소',
 '신일해피트리아파트 앞',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '양강중학교앞 교차로',
 '서울시립대 정문 앞',
 '아차산역4번출구',
 '신당 래미안 버스정류장',
 '서울시립대 정문 앞',
 '합정동주민센터 앞',
 '광진광장 교통섬',
 '솔리스타오피스텔(공덕동주민센터)',
 '서울강월초등학교 앞',
 '아차산역4번출구',
 '가산아네스트 오피스텔 앞',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 '아차산역4번출구',
 '중랑구청',
 'KT앞',
 '아차산역4번출구',
 'LH강남힐스테이트아파트',
 '봉원고가차도 밑',
 '합정동주민센터 앞',
 '역삼빌딩 앞(하나은행 옆)',
 '중랑구청',
 '우장산역 3번출구',
 '아차산역4번출구',
 '서울시립대 정문 앞',
 '서울남부출입국관리소',
 '광진광장 교통섬',
 '신일해피트리아파트 앞',
 '중랑구청',
 '화곡터널입구교차로',
 '신일해피트리아파트 앞',
 '합정동주민센터 앞',
 '온곡초교 교차로',
 '솔리스타오피스텔(공덕동주민센터)',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '신당 래미안 버스정류장',
 '서울남부출입국관리소',
 '신일해피트리아파트 앞',
 '중랑구청',
 '월계프라자',
 '아차산역4번출구',
 '솔리스타오피스텔(공덕동주민센터)',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 '대한항공 인력개발센터',
 '아차산역4번출구',
 '솔리스타오피스텔(공덕동주민센터)',
 '서울강월초등학교 앞',
 '중랑구청',
 '우장산역 3번출구',
 '화곡터널입구교차로',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 'KT앞',
 '원묵고등학교',
 '중랑구청',
 '원묵고등학교',
 '봉원고가차도 밑',
 '여의나루역 1번출구 앞',
 '원묵고등학교',
 '아차산역4번출구',
 '우장산역 3번출구',
 '여의나루역 1번출구 앞',
 '상왕십리역 1번출구',
 '신일해피트리아파트 앞',
 '월계프라자',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '아차산역4번출구',
 '서울남부출입국관리소',
 '아차산역4번출구',
 '중랑구청',
 '서울남부출입국관리소',
 '신일해피트리아파트 앞',
 '가산아네스트 오피스텔 앞',
 '여의나루역 1번출구 앞',
 '여의나루역 1번출구 앞',
 '여의나루역 1번출구 앞',
 '여의나루역 1번출구 앞',
 '여의나루역 1번출구 앞',
 '온곡초교 교차로',
 '온곡초교 교차로',
 '광진광장 교통섬',
 'KT앞',
 '신당 래미안 버스정류장',
 '아차산역4번출구',
 '신당 래미안 버스정류장',
 '원묵고등학교',
 '온곡초교 교차로',
 '우장산역 3번출구',
 '아차산역4번출구',
 '광진광장 교통섬',
 '서울강월초등학교 앞',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '동대문역사문화공원역 1번출구 뒤편',
 '서울남부출입국관리소',
 '광진광장 교통섬',
 '합정동주민센터 앞',
 '봉원고가차도 밑',
 '서울남부출입국관리소',
 '화곡터널입구교차로',
 '온곡초교 교차로',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '양강중학교앞 교차로',
 '솔리스타오피스텔(공덕동주민센터)',
 '중랑구청',
 '아차산역4번출구',
 'KT앞',
 '신일해피트리아파트 앞',
 '온곡초교 교차로',
 '온곡초교 교차로',
 '여의나루역 1번출구 앞',
 '봉원고가차도 밑',
 'LH강남힐스테이트아파트',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 'LH강남힐스테이트아파트',
 '대한항공 인력개발센터',
 '우장산역 3번출구',
 '대한항공 인력개발센터',
 '양강중학교앞 교차로',
 '상왕십리역 1번출구',
 '월계프라자',
 '신일해피트리아파트 앞',
 '서울시립대 정문 앞',
 '원묵고등학교',
 '서울강월초등학교 앞',
 '월계프라자',
 '온곡초교 교차로',
 'KT앞',
 '월계프라자',
 '동대문역사문화공원역 1번출구 뒤편',
 'LH강남힐스테이트아파트',
 '아차산역4번출구',
 'LH강남힐스테이트아파트',
 '신일해피트리아파트 앞',
 '월계프라자',
 '신일해피트리아파트 앞',
 'KT앞',
 '남산도서관 앞',
 '신일해피트리아파트 앞',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '서울남부출입국관리소',
 '온곡초교 교차로',
 '중랑구청',
 '중랑구청',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 '여의나루역 1번출구 앞',
 '상왕십리역 1번출구',
 'LH강남힐스테이트아파트',
 '대한항공 인력개발센터',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '청담공원앞 교차로',
 '아차산역4번출구',
 '아차산역4번출구',
 '신일해피트리아파트 앞',
 '신당 래미안 버스정류장',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '상왕십리역 1번출구',
 '우장산역 3번출구',
 '상왕십리역 1번출구',
 '솔리스타오피스텔(공덕동주민센터)',
 '아차산역4번출구',
 '원묵고등학교',
 '신일해피트리아파트 앞',
 '아차산역4번출구',
 '여의나루역 1번출구 앞',
 '우장산역 3번출구',
 '광진광장 교통섬',
 '화곡터널입구교차로',
 '중랑구청',
 '광진광장 교통섬',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '합정동주민센터 앞',
 '신일해피트리아파트 앞',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '우장산역 3번출구',
 '화곡터널입구교차로',
 '합정동주민센터 앞',
 '남산도서관 앞',
 '상왕십리역 1번출구',
 '남산도서관 앞',
 '남산도서관 앞',
 '상왕십리역 1번출구',
 '우장산역 3번출구',
 '아차산역4번출구',
 '삼부르네상스파크빌',
 'LH강남힐스테이트아파트',
 '화곡터널입구교차로',
 '서울남부출입국관리소',
 '서울강월초등학교 앞',
 '화곡터널입구교차로',
 '삼부르네상스파크빌',
 'KT앞',
 '여의나루역 1번출구 앞',
 '여의나루역 1번출구 앞',
 '여의나루역 1번출구 앞',
 '월계프라자',
 '아차산역4번출구',
 '중랑구청',
 '우장산역 3번출구',
 '우장산역 3번출구',
 '솔리스타오피스텔(공덕동주민센터)',
 'KT앞',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 'LH강남힐스테이트아파트',
 '여의나루역 1번출구 앞',
 '온곡초교 교차로',
 '아차산역4번출구',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '화곡터널입구교차로',
 '서울시립대 정문 앞',
 '온곡초교 교차로',
 '우장산역 3번출구',
 '화곡터널입구교차로',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '대한항공 인력개발센터',
 '봉원고가차도 밑',
 '온곡초교 교차로',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '신일해피트리아파트 앞',
 '서울시립대 정문 앞',
 '중랑구청',
 '상왕십리역 1번출구',
 '신당 래미안 버스정류장',
 '온곡초교 교차로',
 '서울남부출입국관리소',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '아차산역4번출구',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '여의나루역 1번출구 앞',
 'KT앞',
 '가산아네스트 오피스텔 앞',
 '아차산역4번출구',
 '우장산역 3번출구',
 '신일해피트리아파트 앞',
 '여의나루역 1번출구 앞',
 '합정동주민센터 앞',
 '서울강월초등학교 앞',
 '여의나루역 1번출구 앞',
 '여의나루역 1번출구 앞',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '광진광장 교통섬',
 '아차산역4번출구',
 '월계프라자',
 '월계프라자',
 '온곡초교 교차로',
 '아차산역4번출구',
 '대한항공 인력개발센터',
 'KT앞',
 '상왕십리역 1번출구',
 '아차산역4번출구',
 'KT앞',
 '삼부르네상스파크빌',
 '원묵고등학교',
 '우장산역 3번출구',
 '봉원고가차도 밑',
 '서울시립대 정문 앞',
 '중랑구청',
 '상왕십리역 1번출구',
 '원묵고등학교',
 '상왕십리역 1번출구',
 '봉원고가차도 밑',
 '우장산역 3번출구',
 '아차산역4번출구',
 '상왕십리역 1번출구',
 '동대문역사문화공원역 1번출구 뒤편',
 '원묵고등학교',
 '남산도서관 앞',
 '가산아네스트 오피스텔 앞',
 '원묵고등학교',
 '서울남부출입국관리소',
 '아차산역4번출구',
 '중랑구청',
 '봉원고가차도 밑',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '서울시립대 정문 앞',
 'KT앞',
 '우장산역 3번출구',
 '신일해피트리아파트 앞',
 'KT앞',
 '신일해피트리아파트 앞',
 '남산도서관 앞',
 '여의나루역 1번출구 앞',
 '합정동주민센터 앞',
 '여의나루역 1번출구 앞',
 '원묵고등학교',
 '광진광장 교통섬',
 '청담공원앞 교차로',
 '서울강월초등학교 앞',
 '우장산역 3번출구',
 '아차산역4번출구',
 'LH강남힐스테이트아파트',
 '온곡초교 교차로',
 '합정동주민센터 앞',
 '봉원고가차도 밑',
 '서울남부출입국관리소',
 '서울강월초등학교 앞',
 '상왕십리역 1번출구',
 '가산아네스트 오피스텔 앞',
 '봉원고가차도 밑',
 '서울남부출입국관리소',
 '여의나루역 1번출구 앞',
 '가산아네스트 오피스텔 앞',
 '청담공원앞 교차로',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '상왕십리역 1번출구',
 '우장산역 3번출구',
 '서울강월초등학교 앞',
 '서울시립대 정문 앞',
 '삼부르네상스파크빌',
 '양강중학교앞 교차로',
 '상왕십리역 1번출구',
 '원묵고등학교',
 '서울시립대 정문 앞',
 '합정동주민센터 앞',
 '신길자이아파트',
 '아차산역4번출구',
 '아차산역4번출구',
 '합정동주민센터 앞',
 '봉원고가차도 밑',
 '서울시립대 정문 앞',
 '삼부르네상스파크빌',
 '화곡터널입구교차로',
 '합정동주민센터 앞',
 '중랑구청',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '화곡터널입구교차로',
 '봉원고가차도 밑',
 '상왕십리역 1번출구',
 '우장산역 3번출구',
 '서울시립대 정문 앞',
 '대한항공 인력개발센터',
 '대한항공 인력개발센터',
 '서울시립대 정문 앞',
 '합정동주민센터 앞',
 '여의나루역 1번출구 앞',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 'KT앞',
 '아차산역4번출구',
 '서울시립대 정문 앞',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '우장산역 3번출구',
 '온곡초교 교차로',
 '광진광장 교통섬',
 '서울시립대 정문 앞',
 '상왕십리역 1번출구',
 '온곡초교 교차로',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '서울시립대 정문 앞',
 '여의나루역 1번출구 앞',
 '남산도서관 앞',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 '합정동주민센터 앞',
 'KT앞',
 '우장산역 3번출구',
 '합정동주민센터 앞',
 '상왕십리역 1번출구',
 '중랑구청',
 '봉원고가차도 밑',
 '서울강월초등학교 앞',
 '광진광장 교통섬',
 '남산도서관 앞',
 '신당 래미안 버스정류장',
 '광진광장 교통섬',
 '상왕십리역 1번출구',
 '아차산역4번출구',
 '서울시립대 정문 앞',
 '광진광장 교통섬',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '상왕십리역 1번출구',
 '우장산역 3번출구',
 '여의나루역 1번출구 앞',
 '신일해피트리아파트 앞',
 '서울강월초등학교 앞',
 '중랑구청',
 '역삼빌딩 앞(하나은행 옆)',
 '월계프라자',
 '아차산역4번출구',
 '광진광장 교통섬',
 '동대문역사문화공원역 1번출구 뒤편',
 '대한항공 인력개발센터',
 '합정동주민센터 앞',
 '아차산역4번출구',
 '가산아네스트 오피스텔 앞',
 '광진광장 교통섬',
 '신길자이아파트',
 '서울시립대 정문 앞',
 '서울시립대 정문 앞',
 '상왕십리역 1번출구',
 '온곡초교 교차로',
 '삼부르네상스파크빌',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '동대문역사문화공원역 1번출구 뒤편',
 '상왕십리역 1번출구',
 '온곡초교 교차로',
 '광진광장 교통섬',
 '동대문역사문화공원역 1번출구 뒤편',
 'KT앞',
 '화곡터널입구교차로',
 '서울시립대 정문 앞',
 '서울강월초등학교 앞',
 '서울강월초등학교 앞',
 '상왕십리역 1번출구',
 '아차산역4번출구',
 '온곡초교 교차로',
 '남산도서관 앞',
 '광진광장 교통섬',
 '남산도서관 앞',
 '서울시립대 정문 앞',
 '서울강월초등학교 앞',
 '동대문역사문화공원역 1번출구 뒤편',
 '월계프라자',
 '서울시립대 정문 앞',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '양강중학교앞 교차로',
 'KT앞',
 '동대문역사문화공원역 1번출구 뒤편',
 '서울시립대 정문 앞',
 '남산도서관 앞',
 '동대문역사문화공원역 1번출구 뒤편',
 '합정동주민센터 앞',
 '우장산역 3번출구',
 '서울강월초등학교 앞',
 '여의나루역 1번출구 앞',
 '온곡초교 교차로',
 '온곡초교 교차로',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '아차산역4번출구',
 '아차산역4번출구',
 '화곡터널입구교차로',
 '중랑구청',
 '양강중학교앞 교차로',
 '대한항공 인력개발센터',
 '아차산역4번출구',
 '동대문역사문화공원역 1번출구 뒤편',
 '합정동주민센터 앞',
 '신일해피트리아파트 앞',
 '광진광장 교통섬',
 '서울시립대 정문 앞',
 '신길자이아파트',
 '우장산역 3번출구',
 '원묵고등학교',
 '대한항공 인력개발센터',
 '가산아네스트 오피스텔 앞',
 '동대문역사문화공원역 1번출구 뒤편',
 '월계프라자',
 '삼부르네상스파크빌',
 '서울남부출입국관리소',
 '신일해피트리아파트 앞',
 'LH강남힐스테이트아파트',
 '중랑구청',
 '신일해피트리아파트 앞',
 '서울남부출입국관리소',
 '온곡초교 교차로',
 '신길자이아파트',
 '신일해피트리아파트 앞',
 '여의나루역 1번출구 앞',
 '월계프라자',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '신일해피트리아파트 앞',
 '신길자이아파트',
 '아차산역4번출구',
 '서울남부출입국관리소',
 '서울남부출입국관리소',
 '화곡터널입구교차로',
 '아차산역4번출구',
 '서울시립대 정문 앞',
 '서울남부출입국관리소',
 '삼부르네상스파크빌',
 '우장산역 3번출구',
 '화곡터널입구교차로',
 '상왕십리역 1번출구',
 'LH강남힐스테이트아파트',
 '가산아네스트 오피스텔 앞',
 '신당 래미안 버스정류장',
 '서울남부출입국관리소',
 '신일해피트리아파트 앞',
 '아차산역4번출구',
 '원묵고등학교',
 '광진광장 교통섬',
 '여의나루역 1번출구 앞',
 '여의나루역 1번출구 앞',
 '서울남부출입국관리소',
 '신일해피트리아파트 앞',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '아차산역4번출구',
 '삼부르네상스파크빌',
 '월계프라자',
 '솔리스타오피스텔(공덕동주민센터)',
 'KT앞',
 '신일해피트리아파트 앞',
 '가산아네스트 오피스텔 앞',
 '신길자이아파트',
 '솔리스타오피스텔(공덕동주민센터)',
 '신일해피트리아파트 앞',
 '삼부르네상스파크빌',
 '청담공원앞 교차로',
 '신길자이아파트',
 '아차산역4번출구',
 '광진광장 교통섬',
 '가산아네스트 오피스텔 앞',
 '서울강월초등학교 앞',
 '역삼빌딩 앞(하나은행 옆)',
 '화곡터널입구교차로',
 '동대문역사문화공원역 1번출구 뒤편',
 '신길자이아파트',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '신일해피트리아파트 앞',
 '원묵고등학교',
 '서울남부출입국관리소',
 '대한항공 인력개발센터',
 '우장산역 3번출구',
 '아차산역4번출구',
 '광진광장 교통섬',
 '여의나루역 1번출구 앞',
 'KT앞',
 '삼부르네상스파크빌',
 '여의나루역 1번출구 앞',
 '대한항공 인력개발센터',
 '청담공원앞 교차로',
 '신일해피트리아파트 앞',
 '아차산역4번출구',
 '서울강월초등학교 앞',
 '광진광장 교통섬',
 'KT앞',
 '삼부르네상스파크빌',
 '여의나루역 1번출구 앞',
 '가산아네스트 오피스텔 앞',
 '청담공원앞 교차로',
 '봉원고가차도 밑',
 '아차산역4번출구',
 '광진광장 교통섬',
 'KT앞',
 '여의나루역 1번출구 앞',
 '가산아네스트 오피스텔 앞',
 '청담공원앞 교차로',
 '신당 래미안 버스정류장',
 '여의나루역 1번출구 앞',
 '청담공원앞 교차로',
 '온곡초교 교차로',
 '신일해피트리아파트 앞',
 '광진광장 교통섬',
 'KT앞',
 '청담공원앞 교차로',
 '우장산역 3번출구',
 '봉원고가차도 밑',
 '아차산역4번출구',
 '서울강월초등학교 앞',
 '광진광장 교통섬',
 'KT앞',
 '가산아네스트 오피스텔 앞',
 '청담공원앞 교차로',
 '신길자이아파트',
 '광진광장 교통섬',
 'KT앞',
 '삼부르네상스파크빌',
 '대한항공 인력개발센터',
 '서울강월초등학교 앞',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 '솔리스타오피스텔(공덕동주민센터)',
 '아차산역4번출구',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '상왕십리역 1번출구',
 '신당 래미안 버스정류장',
 'LH강남힐스테이트아파트',
 '광진광장 교통섬',
 'KT앞',
 'KT앞',
 '여의나루역 1번출구 앞',
 '상왕십리역 1번출구',
 '대한항공 인력개발센터',
 '가산아네스트 오피스텔 앞',
 '청담공원앞 교차로',
 '신당 래미안 버스정류장',
 '우장산역 3번출구',
 '신일해피트리아파트 앞',
 'KT앞',
 '삼부르네상스파크빌',
 '여의나루역 1번출구 앞',
 '대한항공 인력개발센터',
 '광진광장 교통섬',
 '삼부르네상스파크빌',
 '여의나루역 1번출구 앞',
 '광진광장 교통섬',
 '여의나루역 1번출구 앞',
 '원묵고등학교',
 '봉원고가차도 밑',
 '여의나루역 1번출구 앞',
 '삼부르네상스파크빌',
 '서울강월초등학교 앞',
 '서울시립대 정문 앞',
 '광진광장 교통섬',
 '청담공원앞 교차로',
 '광진광장 교통섬',
 '대한항공 인력개발센터',
 '아차산역4번출구',
 'KT앞',
 '상왕십리역 1번출구',
 '여의나루역 1번출구 앞',
 'KT앞',
 '상왕십리역 1번출구',
 '광진광장 교통섬',
 '솔리스타오피스텔(공덕동주민센터)',
 '여의나루역 1번출구 앞',
 '우장산역 3번출구',
 '삼부르네상스파크빌',
 '상왕십리역 1번출구',
 '대한항공 인력개발센터',
 '서울남부출입국관리소',
 '광진광장 교통섬',
 '서울강월초등학교 앞',
 '광진광장 교통섬',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '서울남부출입국관리소',
 '아차산역4번출구',
 '광진광장 교통섬',
 'KT앞',
 '신일해피트리아파트 앞',
 '여의나루역 1번출구 앞',
 '광진광장 교통섬',
 '신길자이아파트',
 '대한항공 인력개발센터',
 '여의나루역 1번출구 앞',
 '서울시립대 정문 앞',
 '서울남부출입국관리소',
 '우장산역 3번출구',
 '동대문역사문화공원역 1번출구 뒤편',
 'KT앞',
 '화곡터널입구교차로',
 '서울남부출입국관리소',
 '아차산역4번출구',
 '서울강월초등학교 앞',
 '상왕십리역 1번출구',
 '합정동주민센터 앞',
 '광진광장 교통섬',
 'KT앞',
 '삼부르네상스파크빌',
 'KT앞',
 '대한항공 인력개발센터',
 '광진광장 교통섬',
 '삼부르네상스파크빌',
 '광진광장 교통섬',
 '동대문역사문화공원역 1번출구 뒤편',
 '대한항공 인력개발센터',
 '아차산역4번출구',
 '대한항공 인력개발센터',
 '중랑구청',
 '상왕십리역 1번출구',
 '아차산역4번출구',
 '합정동주민센터 앞',
 '아차산역4번출구',
 '상왕십리역 1번출구',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '삼부르네상스파크빌',
 '우장산역 3번출구',
 '신길자이아파트',
 '서울시립대 정문 앞',
 'KT앞',
 '서울남부출입국관리소',
 '아차산역4번출구',
 '역삼빌딩 앞(하나은행 옆)',
 '원묵고등학교',
 '온곡초교 교차로',
 '서울시립대 정문 앞',
 '가산아네스트 오피스텔 앞',
 '아차산역4번출구',
 '서울남부출입국관리소',
 '서울남부출입국관리소',
 '온곡초교 교차로',
 '봉원고가차도 밑',
 '솔리스타오피스텔(공덕동주민센터)',
 '광진광장 교통섬',
 '우장산역 3번출구',
 '신당 래미안 버스정류장',
 '합정동주민센터 앞',
 '원묵고등학교',
 '여의나루역 1번출구 앞',
 '서울시립대 정문 앞',
 'LH강남힐스테이트아파트',
 '여의나루역 1번출구 앞',
 '합정동주민센터 앞',
 '중랑구청',
 '대한항공 인력개발센터',
 '서울남부출입국관리소',
 '중랑구청',
 '서울남부출입국관리소',
 '신당 래미안 버스정류장',
 '여의나루역 1번출구 앞',
 '중랑구청',
 '서울남부출입국관리소',
 '아차산역4번출구',
 'KT앞',
 '상왕십리역 1번출구',
 '솔리스타오피스텔(공덕동주민센터)',
 '온곡초교 교차로',
 '서울남부출입국관리소',
 '원묵고등학교',
 '합정동주민센터 앞',
 'LH강남힐스테이트아파트',
 '화곡터널입구교차로',
 '상왕십리역 1번출구',
 '화곡터널입구교차로',
 '서울남부출입국관리소',
 '서울남부출입국관리소',
 '원묵고등학교',
 '동대문역사문화공원역 1번출구 뒤편',
 '서울남부출입국관리소',
 '합정동주민센터 앞',
 'KT앞',
 'KT앞',
 '중랑구청',
 '여의나루역 1번출구 앞',
 '온곡초교 교차로',
 '서울남부출입국관리소',
 '여의나루역 1번출구 앞',
 'KT앞',
 '남산도서관 앞',
 'KT앞',
 '원묵고등학교',
 '서울시립대 정문 앞',
 '서울남부출입국관리소',
 '솔리스타오피스텔(공덕동주민센터)',
 'KT앞',
 '아차산역4번출구',
 '서울시립대 정문 앞',
 '여의나루역 1번출구 앞',
 '원묵고등학교',
 '동대문역사문화공원역 1번출구 뒤편',
 'KT앞',
 '신일해피트리아파트 앞',
 '가산아네스트 오피스텔 앞',
 '우장산역 3번출구',
 '양강중학교앞 교차로',
 'KT앞',
 '서울남부출입국관리소',
 '서울남부출입국관리소',
 '신길자이아파트',
 '여의나루역 1번출구 앞',
 '원묵고등학교',
 '서울시립대 정문 앞',
 '광진광장 교통섬',
 '원묵고등학교',
 '봉원고가차도 밑',
 'KT앞',
 '우장산역 3번출구',
 '서울남부출입국관리소',
 '중랑구청',
 '월계프라자',
 '상왕십리역 1번출구',
 '온곡초교 교차로',
 '상왕십리역 1번출구',
 '청담공원앞 교차로',
 '여의나루역 1번출구 앞',
 '솔리스타오피스텔(공덕동주민센터)',
 '청담공원앞 교차로',
 '온곡초교 교차로',
 '신길자이아파트',
 '남산도서관 앞',
 '신일해피트리아파트 앞',
 '상왕십리역 1번출구',
 '서울남부출입국관리소',
 '서울시립대 정문 앞',
 '서울남부출입국관리소',
 '아차산역4번출구',
 '원묵고등학교',
 '중랑구청',
 '대한항공 인력개발센터',
 '서울남부출입국관리소',
 '서울강월초등학교 앞',
 '서울남부출입국관리소',
 '온곡초교 교차로',
 '중랑구청',
 '상왕십리역 1번출구',
 '합정동주민센터 앞',
 '서울남부출입국관리소',
 '여의나루역 1번출구 앞',
 '우장산역 3번출구',
 '온곡초교 교차로',
 '서울강월초등학교 앞',
 '서울남부출입국관리소',
 '신길자이아파트',
 '아차산역4번출구',
 '서울시립대 정문 앞',
 '광진광장 교통섬',
 '중랑구청',
 '상왕십리역 1번출구',
 '온곡초교 교차로',
 '삼부르네상스파크빌',
 '동대문역사문화공원역 1번출구 뒤편',
 '중랑구청',
 '온곡초교 교차로',
 '신길자이아파트',
 '남산도서관 앞',
 '아차산역4번출구',
 '상왕십리역 1번출구',
 '여의나루역 1번출구 앞',
 '여의나루역 1번출구 앞',
 '아차산역4번출구',
 '광진광장 교통섬',
 '우장산역 3번출구',
 '월계프라자',
 '합정동주민센터 앞',
 '서울시립대 정문 앞',
 '양강중학교앞 교차로',
 '동대문역사문화공원역 1번출구 뒤편',
 '서울시립대 정문 앞',
 '화곡터널입구교차로',
 '합정동주민센터 앞',
 '서울시립대 정문 앞',
 '청담공원앞 교차로',
 '신당 래미안 버스정류장',
 '합정동주민센터 앞',
 'KT앞',
 '상왕십리역 1번출구',
 '여의나루역 1번출구 앞',
 '우장산역 1번출구옆(우장산아이파크105동앞)',
 '서울남부출입국관리소',
 '남산도서관 앞',
 '신일해피트리아파트 앞',
 '신당 래미안 버스정류장',
 '봉원고가차도 밑',
 '월계프라자',
 '서울강월초등학교 앞',
 'KT앞',
 '양강중학교앞 교차로',
 '대한항공 인력개발센터',
 '온곡초교 교차로',
 '신일해피트리아파트 앞',
 '서울시립대 정문 앞',
 '여의나루역 1번출구 앞',
 '동대문역사문화공원역 1번출구 뒤편',
 '여의나루역 1번출구 앞',
 '남산도서관 앞',
 '서울남부출입국관리소',
 '서울남부출입국관리소',
 '원묵고등학교',
 ...]

In [199]:
# 대여일자 - 대여시간 - 대여소번호 별로 정렬
rental_2301.sort_values(by=['대여일자', '대여시간', '대여소번호'], inplace=True)

In [200]:
# 인덱스 초기화
rental_2301 = rental_2301.reset_index(drop=True)

In [201]:
rental_2301

             대여일자  대여시간  대여소번호                대여소명  이용건수
0      2023-01-01     0    207        여의나루역 1번출구 앞     1
1      2023-01-01     0    207        여의나루역 1번출구 앞     1
2      2023-01-01     0    213                 KT앞     1
3      2023-01-01     0    434        신당 래미안 버스정류장     1
4      2023-01-01     0    474  동대문역사문화공원역 1번출구 뒤편     1
...           ...   ...    ...                 ...   ...
22259  2023-01-31    23   3758          서울남부출입국관리소     1
22260  2023-01-31    23   3758          서울남부출입국관리소     1
22261  2023-01-31    23   4009               월계프라자     1
22262  2023-01-31    23   4009               월계프라자     1
22263  2023-01-31    23   4591             신길자이아파트     1

[22264 rows x 5 columns]

In [202]:
# 대여일자 순환 위한 날짜 리스트 생성
month_date = []

for i in range(1, 32):
    month = '2023-01-'
    if i < 10:
        date = '0' + str(i)
    else:
        date = str(i)
    month_date.append(month + date)

In [203]:
month_date

['2023-01-01',
 '2023-01-02',
 '2023-01-03',
 '2023-01-04',
 '2023-01-05',
 '2023-01-06',
 '2023-01-07',
 '2023-01-08',
 '2023-01-09',
 '2023-01-10',
 '2023-01-11',
 '2023-01-12',
 '2023-01-13',
 '2023-01-14',
 '2023-01-15',
 '2023-01-16',
 '2023-01-17',
 '2023-01-18',
 '2023-01-19',
 '2023-01-20',
 '2023-01-21',
 '2023-01-22',
 '2023-01-23',
 '2023-01-24',
 '2023-01-25',
 '2023-01-26',
 '2023-01-27',
 '2023-01-28',
 '2023-01-29',
 '2023-01-30',
 '2023-01-31']

In [206]:
# 대여소별 시간대별 이용건수 집계를 위한 새로운 데이터프레임 생성
# 변수 : 대여일자 - 대여시간대 - 대여소번호 - 대여소명 - 이용건수

station_rental_2301 = pd.DataFrame(columns=['대여일자', '대여시간', '대여소번호', '대여소명', '이용건수'])
station_rental_2301

Empty DataFrame
Columns: [대여일자, 대여시간, 대여소번호, 대여소명, 이용건수]
Index: []

In [207]:
# 집계할 데이터 프레임의 열, 행 생성
# 대여소별 일-시간대-이용건수 생성 : 이용건수는 모두 0으로 설정 (추후 23년 1월 데이터를 보며 추가)
# 표본 대여소 별로 날짜 - 대여시간 - 이용건수가 담긴 데이터 생성

# idx : 집계 데이터의 인덱스
idx = 0

for date in month_date:
    for s_index in sample.index:
        for time in range(24):
            new_line = [date, time, sample.loc[s_index]['대여소번호'], sample.loc[s_index]['대여소명'], 0]
            station_rental_2301.loc[idx] = new_line
            idx += 1

In [208]:
station_rental_2301

             대여일자 대여시간 대여소번호         대여소명 이용건수
0      2023-01-01    0   574     아차산역4번출구    0
1      2023-01-01    1   574     아차산역4번출구    0
2      2023-01-01    2   574     아차산역4번출구    0
3      2023-01-01    3   574     아차산역4번출구    0
4      2023-01-01    4   574     아차산역4번출구    0
...           ...  ...   ...          ...  ...
22315  2023-01-31   19  1175  대한항공 인력개발센터    0
22316  2023-01-31   20  1175  대한항공 인력개발센터    0
22317  2023-01-31   21  1175  대한항공 인력개발센터    0
22318  2023-01-31   22  1175  대한항공 인력개발센터    0
22319  2023-01-31   23  1175  대한항공 인력개발센터    0

[22320 rows x 5 columns]

In [230]:
# 23년 01월 대여정보를 통해 집계 데이터프레임에 대여건수 추가

# 시간대별 이용건수 데이터프레임을 순환하며 이용건수를 대여소+시간대별 데이터프레임에 추가
for idx in rental_2301.index:
    info = rental_2301.loc[idx]
    date = info['대여일자']
    time = info['대여시간']
    station_num = info['대여소번호']
    # staion_name = info['대여소명'] 은 불필요
    rental_num = info['이용건수']
    
    # 수정 (이용건수 추가할) 인덱스를 위 조건에 따라 추출
    modify_index = station_rental_2301[(station_rental_2301['대여일자'] == date) & (station_rental_2301['대여시간'] == time) & (station_rental_2301['대여소번호'] == station_num)].index
    # 수정 인덱스의 이용건수에 추가
    station_rental_2301.loc[modify_index, '이용건수'] += rental_num

In [238]:
# 이용건수 정보가 추가됨
station_rental_2301

             대여일자 대여시간 대여소번호         대여소명 이용건수
0      2023-01-01    0   574     아차산역4번출구    0
1      2023-01-01    1   574     아차산역4번출구    1
2      2023-01-01    2   574     아차산역4번출구    0
3      2023-01-01    3   574     아차산역4번출구    0
4      2023-01-01    4   574     아차산역4번출구    0
...           ...  ...   ...          ...  ...
22315  2023-01-31   19  1175  대한항공 인력개발센터    4
22316  2023-01-31   20  1175  대한항공 인력개발센터    1
22317  2023-01-31   21  1175  대한항공 인력개발센터    0
22318  2023-01-31   22  1175  대한항공 인력개발센터    4
22319  2023-01-31   23  1175  대한항공 인력개발센터    1

[22320 rows x 5 columns]

In [272]:
# 평일인지, 평일이 아닌지(주말, 공휴일)는 대여건수에 영향을 미치는 변수
# 대여일자가 평일인지 주말인지 datetime의 weekday() 함수를 통해 요일을 구분
# 0, 1, 2, 3, 4 = 월, 화, 수, 목, 금 = 평일
# 5, 6 = 토, 일 = 주말

import datetime

# 평일구분 열 추가 -> 값 : '평일' or '평일 외'가 될 것

# 빈 열 생성
station_rental_2301['평일구분'] = ''

for idx in station_rental_2301.index:
    date = station_rental_2301.loc[idx]['대여일자']
    # 기존 문자열을 datetime 변수로 변환
    convert_date = datetime.datetime.strptime(date, '%Y-%m-%d')
    # 요일 반환 (0~6)
    day = convert_date.weekday()
    if day < 5:
        # 평일이면 '평일'로 값 변경
        station_rental_2301.loc[idx, '평일구분'] = '평일'
    else:
        # 주말이면 '평일 외'로 값 변경, 추후 공휴일도 '평일 외'로 분류 예정
        station_rental_2301.loc[idx, '평일구분'] = '평일 외'

In [287]:
station_rental_2301

             대여일자 대여시간 대여소번호         대여소명 이용건수  평일구분
0      2023-01-01    0   574     아차산역4번출구    0  평일 외
1      2023-01-01    1   574     아차산역4번출구    1  평일 외
2      2023-01-01    2   574     아차산역4번출구    0  평일 외
3      2023-01-01    3   574     아차산역4번출구    0  평일 외
4      2023-01-01    4   574     아차산역4번출구    0  평일 외
...           ...  ...   ...          ...  ...   ...
22315  2023-01-31   19  1175  대한항공 인력개발센터    4    평일
22316  2023-01-31   20  1175  대한항공 인력개발센터    1    평일
22317  2023-01-31   21  1175  대한항공 인력개발센터    0    평일
22318  2023-01-31   22  1175  대한항공 인력개발센터    4    평일
22319  2023-01-31   23  1175  대한항공 인력개발센터    1    평일

[22320 rows x 6 columns]

In [286]:
rental_2301

             대여일자  대여시간  대여소번호                대여소명  이용건수
0      2023-01-01     0    207        여의나루역 1번출구 앞     1
1      2023-01-01     0    207        여의나루역 1번출구 앞     1
2      2023-01-01     0    213                 KT앞     1
3      2023-01-01     0    434        신당 래미안 버스정류장     1
4      2023-01-01     0    474  동대문역사문화공원역 1번출구 뒤편     1
...           ...   ...    ...                 ...   ...
22259  2023-01-31    23   3758          서울남부출입국관리소     1
22260  2023-01-31    23   3758          서울남부출입국관리소     1
22261  2023-01-31    23   4009               월계프라자     1
22262  2023-01-31    23   4009               월계프라자     1
22263  2023-01-31    23   4591             신길자이아파트     1

[22264 rows x 5 columns]